### ISSUE TITLE
Concatenation of nested rules not working

### ISSUE THREAD

**Issue by alsoicode** [dotless/dotless#109]
When writing a rule such as...

``` css
ul
{
    li
    {
        display: inline-block;

        &.active
        {
            background-color: black;
        }
    }
}
```

...and serving the .less file using the dotless.Core dll, The stylesheet will be incomplete, ending before the offending rule, in this case the ul rule. Sorry for the formatting weirdness. Github markdown doesn't seem to want to honor ```css
