### ISSUE TITLE
Support namespaced variables

### ISSUE THREAD

**Issue by Daniel15** [dotless/dotless#133]
From what I can see, LESS supports namespaced variables like this:

``` css
#defaults {
  @heading-color: #EE3322;
}
```

Which you use like this:

``` css
h1 {
  color: #defaults[@heading-color];
}
```

As far as I can tell, dotLESS doesn't support this.

See http://coding.smashingmagazine.com/2010/12/06/using-the-less-css-preprocessor-for-smarter-style-sheets/ (section 5 - Namespaces and Accessors) for an example.
