### ISSUE TITLE
e("\9") doesn't work as expected

### ISSUE THREAD

**Issue by Daniel15** [dotless/dotless#161]
This is often used as an IE hack - Any CSS property with a "\9" at the end will be matched in IE 8 and below (in both quirks and standards modes). This is used in Twitter bootstrap for instance.

See:
http://webdood.com/?p=57
http://webdesignerwall.com/tutorials/css-specific-for-internet-explorer

An example:

``` css
@white: #FFFFFF;

#blah {
  background-color: darken(@white, 10%);
  background-color: darken(@white, 15%) e("\9");
} 
```

This should be output as:

``` css
#blah {
  background-color: #e6e6e6;
  background-color: #d9d9d9 \9;
}
```

But dotLESS outputs:

``` css
#blah {
  background-color: #e6e6e6;
  background-color: #d9d9d9 9;
}
```

The slash goes missing.

Expected result: DotLESS should have the same output as LessJS does.
