### ISSUE TITLE
Add a current directory option to DotlessConfiguration

### ISSUE THREAD

**Issue by katbyte** [dotless/dotless#204]
I am using dotLess in such a way i need to dynamically set the current directory Import uses to one different then the current application working directory. I currently pre-process the .less file, and am toying with the idea of forking dotLess and adding it myself. 

Is this a planned feature? and/or is there a reason this hasn't been added as an option?

**Comment by rytmis** [comment]
I'm wondering about this one... is it really necessary to set the current directory, as opposed to just treating the directory containing the "entry point" file as the "current directory"? I don't see much value in doing anything else, so maybe this is something I could implement without exposing Yet Another Configuration Switch?

**Comment by rytmis** [comment]
Meh. I thought about this some more, and obviously that won't work when the initial source comes from something other than a file. Oh well. :-)

**Comment by rytmis** [comment]
1d7ac01 exposes the current directory as a settable property on ILessEngine -- which passes it on to Parser, which passes it on to Importer.

**Comment by hermankan** [comment]
The fix does not work when a LESS being compiled contains an `@import` link to another LESS file, e.g. "bootrstrap/bootstrap.less". It just ignores the CurrentDirectory setting when resolving the path.

**Comment by rytmis** [comment]
Do you think you could whip up a minimal test case I could use to see what's going on?

**Comment by hermankan** [comment]
Here is the test structure:

```
C:\
	sample.less
	images\
		sample.gif
	subfolder\
		module.less
		images\
			module.gif
```

```less
// C:\test\sample.less
@import "subfolder/module.less";
.sample {
	background-image: url('images/sample.gif');
}
```

```less
// C:\test\subfolder\module.less
.module {
	background-image: url('images/module.gif');
}
```

```c#
// Test.cs
var lessFile = new FileInfo("C:\\test\\sample.less"");
var lessEngine = new EngineFactory().GetEngine();
lessEngine.CurrentDirectory = lessFile.DirectoryName;
string cssContent = lessEngine.TransformToCss(lessFile.OpenText().ReadToEnd(), null);
```
