### ISSUE TITLE
Space added to font family value during compilation

### ISSUE THREAD

**Issue by JustinBeckwith** [dotless/dotless#224]
A user submitted an issue with a project I built using dotless:
https://github.com/JustinBeckwith/OrangeBits/issues/5

If you have a less file with the following class:

```css
.spaceTest {
    font-family: MuseoSans-500, "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, "Lucida Grande", sans-serif; 
} 
```

It is compiled into this:

```css
.spaceTest {
  font-family: MuseoSans- 500, "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, "Lucida Grande", sans-serif;
}
```

It's hard to see, but now there is a space between MuseoSans- and the number 500.  This breaks the resulting css output.
