### ISSUE TITLE
Mathematical operations drop unit from result

### ISSUE THREAD

**Issue by Ag0n** [dotless/dotless#227]
I'm currently storing all of my shared variables in a file called variables.less and importing this file into a few other less files used to generate the CSS for my site.

I'm running into a bug where my original variables are specified as being in em, but the CSS put out by dotless has no units.

For example this is what a selection from my variables file looks like:

```css
@spacingSize:			1.5em;
@footerFontSize:		1.2em;
```
and an import with a rule from another file:

```css
@import		"variables.less";

#copyright {
	left:			@spacingSize / @footerFontSize;
}
```

And this is what comes out in my browser:

```css
#copyright {
      left: 1.25;
}
```

which is invalid because it has no units of measure. Right now I'm currently working around this issue by adding a * 1em to the end of any calculated rules.

As a side note, this file was built by a coworker that is currently using these exact files with the Express platform on linux for another project and the units are coming out correctly there, suggesting that this is just odd behavior from Dotless.
