### ISSUE TITLE
"variable ... is undefined" on block that works in less.js

### ISSUE THREAD

**Issue by CompositeC1** [dotless/dotless#241]
Output from http://www.boottheme.com/ break dotLESS, the output works in less.js. 

Boiled down repro:
```css
@navbarBackground:	darken(@navbarBackgroundHighlight, 10%);
@navbarBackgroundHighlight:	#FAFDF2;

body {
 background-image: -moz-linear-gradient(top, @navbarBackgroundHighlight, @navbarBackground);
}
```

The fix is obviously to ensure `@navbarBackgroundHighlight` is declared before `@navbarBackground`, but less.js support it fine and when an automated tool emit it it's a drag to have to manually update the generated file after each export.

Also the error details are shown as goo (chars like �)  or empty result if `<dotless caching="true" />` is set in web.config, but I'm guessing this is covered by https://github.com/dotless/dotless/pull/235

[offtopic]A big thank you to the project members for spending their time on building dotless and sharing their work. Much appreciated :)[/offtopic]

UPDATE: The latest release of Twitter Bootstrap expose this issue, so going though http://www.boottheme.com/ is no longer needed. Just use Bootstrap 2.1
