### ISSUE TITLE
Error calling mixin when passing escaped string

### ISSUE THREAD

**Issue by sjonner** [dotless/dotless#264]
Just updated from version 1.2.1.0 to 1.3.1.0 which failed to parse a less stylesheet where as 1.2.1.0 succeeded.

An exception was thrown when using the following mixin:

``` css
.box-shadow-manual() {
    -moz-box-shadow: @arguments;
    -webkit-box-shadow: @arguments;
    box-shadow: @arguments;
}
```

The implementation of the mixin:

``` css
.test1 { .box-shadow-manual(~"0 3px 4px -2px #666, 2px 0 3px -3px #333, -2px 0 3px -3px #333"); }
.test2 { .box-shadow-manual(~"0 2px 2px 0 #888, 0 5px 5px -4px #888"); }
```

This code parsed ok in 1.2.1.0, but an exception is thrown in 1.3.1.0 for the same less code.
I was able to fix it in the less code by adding a dummy parameter name:

``` css
.box-shadow-manual(@dummy) {
    -moz-box-shadow: @arguments;
    -webkit-box-shadow: @arguments;
    box-shadow: @arguments;
}
```

Expected behaviour is that of version 1.2.1.0, since the dummy argument isn't used anyway. It seems an escaped string isn't passed in `@arguments` keyword?
