### ISSUE TITLE
Background-size in shorthand causes parser error

### ISSUE THREAD

**Issue by n3ps** [dotless/dotless#301]
Sample:

```css
#test {
	background: #fff url('image.png') no-repeat 50% / contain;
}
```

Results in: 
```
Expected number in right hand side of /
```

Found a workaround by escaping ~"/" but would love to see it implemented as-is.
