### ISSUE TITLE
No Unit Function

### ISSUE THREAD

**Issue by zjr-trov** [dotless/dotless#309]
LESS has a unit function for swapping units, dotless seems not to.

e.g.
```CSS
@baseLine: 1em;
@lineHeight: ((@baseLine * 1.5) - (1/16));

.rule {
  line-height: unit(@lineHeight, rem);
}
```
should result in:
```CSS
.rule {
  line-height: 1.4375rem;
}
```
but instead results in
```CSS
.rule {
  line-height: unit(1.4375em, rem);
}
```
