### ISSUE TITLE
Overriding global variables should behave like less.js

### ISSUE THREAD

**Issue by TheYves** [dotless/dotless#312]
I'm not sure if it's related to issue #144 but dotless should, at least in my opinion, behave exactly like less.js if it comes to overriding global variables. About 6 months ago, they decided in a GitHub issue that LESS is always using the last definition of a variable. 

Issue: https://github.com/less/less.js/issues/297

So this LESS snippet:
```css
// declaring foo
@foo: #ccc;

// using variable foo
.bar {
    color: @foo;
}

// overriding foo
@foo: #f00;
```
should compile to:
```css
.bar {
  color: #ff0000;
}
```
and __not__ to:
```css
.bar {
  color: #cccccc;
}
```
I give you a good example where this is totally useful: If you use Twitters bootstrap with dotless and you want to override their global variables, you have to edit their bootstrapp.less and add an import to your own variables.less or you would copy the whole content of their bootstrap.less and create a custom-bootstrap.less.

But in less.js you can just import their bootstrap.less and after that, you override their global variables. This way, the whole bootstrap directory can remain untouched and you don't need a lot effort updating Twitters bootstrap.
