### ISSUE TITLE
Support calling mixins defined using parent selectors

### ISSUE THREAD

**Issue by zjr-trov** [dotless/dotless#314]
In a LESS.js parser I can use namespaces much more freely than .LESS.  The problem seems to stem from using an ampersand when namespacing.

So I *should* be able to write
```LESS
.btn {
  color: red;
  &.btn-blue {
    color: blue;
  }
}
```
And then reuse it elsewhere like:
```LESS
.item {
  .btn.btn-blue;
}

// or...

.item {
  .btn .btn-blue;
}

// or...

.item {
  .btn > .btn-blue;
}
```
Which should produce:
```CSS
.item {
  color: blue;
}
```

But instead causes an error because the mixin 'doesn't exist'.  There appears to be no way to use a mixin that is namespaced with a joining ampersand.  So I have to write all of my selectors twice if I want them to be available as both conjoined classes and mixins.
