### ISSUE TITLE
extend() language feature is missing from 1.4

### ISSUE THREAD

**Issue by danjkennedy** [dotless/dotless#355]
Feature is outlined here: http://www.lesscss.org/#-extend

**Basic example**

``` css
.first {
    width: 100%;
}
.second:extend(.first) {
    color: red;
}
```

should produce

``` css
.first,
.second {
    width: 100%;
}
.second {
    color: red;
}
```

This will compile, but will not produce the expected result. The compiled css looks exactly like the less. There is alternative syntax for this feature, which looks a bit like...

``` css
.first {
    width: 100%;
}
.second {
    color: red;
    &:extend(.first);
}
```

This throws an exception

```
Expected '}' but found ':' on line 6 in file [...]:
  [5] : color: red;
  [6] : &:extend(.first);
    ----^
  [7] : }
[Done - Failed]
```
