### ISSUE TITLE
Space rendered in variable result 

### ISSUE THREAD

**Issue by motowilliams** [dotless/dotless#368]
When using a variable value with a numeric character it will add a space when used in a Id css selector

``` less
@wiget-container: widget-container-8675309;

#@{wiget-container} {
    color: blue;
}
```

should result in 

``` css
#widget-container-8675309 {
  color: blue;
}
```

The spec doesn't seem to say anything that should make this illegal syntax and it works with other compilers — http://www.w3.org/TR/html5/dom.html#the-id-attribute

I've add a failing unit test for a repro https://github.com/motowilliams/dotless/commit/900de3cec28b4cced1386c8b9c3605939aae190f

```
Errors and Failures:
1) Test Failure : dotless.Test.Specs.VariablesFixture.NumericVariables
 Expected string length 44 but was 45. Strings differ at index 18.
  Expected: "#widget-container-8675309 {\n  color: blue;\n}"
  But was:  "#widget-container- 8675309 {\n  color: blue;\n}"
```
