### ISSUE TITLE
extend() is implemented incorrectly for nested declarations

### ISSUE THREAD

**Issue by j2jensen** [dotless/dotless#384]
The following LESS:

```less
.btn-primary {
  color: white;
}

a:link {
  color: blue;
}

a:link {
    &.btn-primary:extend(.btn-primary){}
}
```

Is translated to:

```css
.btn-primary,
a:link .btn-primary {
  color: white;
}
a:link {
  color: blue;
}
```

Notice the extra space in `a:link .btn-primary`. This should be `a:link.btn-primary`.
