### ISSUE TITLE
extend() only includes first outer selector when nested with additional selector

### ISSUE THREAD

**Issue by j2jensen** [dotless/dotless#385]
```less
.btn-primary {
  color: white;
}

a:active,a:visited
{
  color: blue;
}

a:active, a:visited {
    &.btn-primary:extend(.btn-primary){}
}
```

Translates to:

```css
.btn-primary,
a:active .btn-primary {
  color: white;
}
a:active,
a:visited {
  color: blue;
}
```

Note that `a:visited` was omitted from the first rule. (The extra space before `.btn-primary` is reported as issue #384).

If I change the last CSS rule to this:

```less
a:active.btn-primary, a:visited.btn-primary {
        &:extend(.btn-primary);
}
```

It works just fine:

```css
.btn-primary,
a:active.btn-primary,
a:visited.btn-primary {
  color: white;
}
a:active,
a:visited {
  color: blue;
}
```
