### ISSUE TITLE
1.4.1 breaks mixin usage without parens

### ISSUE THREAD

**Issue by eamodio** [dotless/dotless#387]
Hi - just upgraded to 1.4.1 and it now errors out when compiling the following less (which worked prior to 1.4.1):
```css
.link-reset {
  text-decoration: none !important;
}

.link-reset (@border) when (@border = noborder) {
  border: 0 none;
}

.foo {
    .link-reset;
}

.bar {
    .link-reset(noborder);
}
```

Here is the error returned:
```
No matching definition was found for `.link-reset()` on line 10 in file 'foo.less':                                                                                     
  [9]: .foo {                                                                                       
 [10]:     .link-reset;                                                                             
       ----^                                                                                        
 [11]: }                                                                                            
[Done - Failed]                                                                                     
```

If I change `.link-reset {` to `.link-reset() {` it will compile, but the output isn't what is desired.

Let me know if you need anymore information.
Eric
