### ISSUE TITLE
Fails to compile &:extend in loop.

### ISSUE THREAD

**Issue by Petoj87** [dotless/dotless#402]
If i try to compile the following less:

```less
.clearfix() {
  &:before,
  &:after {
    content: " "; // 1
    display: table; // 2
  }
  &:after {
    clear: both;
  }
}

.make-row() {
  &:extend(.clearfix all);
}

.make-rows() {
  .row(@index) when (@index < 10) {
    .row@{index} {
      height: 10 * @index;
      .make-row();
    }
    .row(@index + 1);
  }
  .row(1);
}

.clearfix
{
  .clearfix();
}

.make-rows();
```

with dotless 1.4.1.0 i get the following error 
```
Compilation failed: Value cannot be null.
Parameter name: source
at dotless.Core.Parser.Infrastructure.Extender.AddExtension(Selector selector, Env env)
...
```

While other compilers get the correct output (http://winless.org/online-less-compiler is one of them).

**Comment by rytmis** [comment]
Managed to simplify the test case a bit after a bit of iterating.

```less
.extension {
  color: red;
}

.mixin() {
    .rule {
        &:extend(.extension all);
    }
}

.mixin();
```
