### ISSUE TITLE
Escaping string literals

### ISSUE THREAD

**Issue by hempels** [dotless/dotless#426]
I've run into an issue where I can't find a way to successfully escape a unicode character value being passed into content: for a pseudo-class.

e.g.
blockquote {
    &:before {
        content: ~"'\201c'";   /* &ldquo; */
    }
    &:after {
        content: ~"'\201d'";   /* &rdquo; */
    }
}

No matter what I put in the value for content:, I cannot get dotLess to output '\201c' & '\201d', it always outputs the replaced unicode characters which then create encoding problems.

**Comment by rytmis** [comment]
Didn't reproduce for me with the latest official release. I pasted your example into a test document, ran the compiler and got:

```less
blockquote:before {
  content: '\201c';
}
blockquote:after {
  content: '\201d';
}
```
