### ISSUE TITLE
Namespaced @imports 

### ISSUE THREAD

**Issue by rytmis** [dotless/dotless#430]
With the following files:

test.less:
```less
.foo {
  background-color: black;
}
```

main.less:
```less
.bar {
  @import "test.less";
}
```

Compiling main.less with less.js results in:

```css
.bar .foo{background-color:#000}
```

Whereas dotless produces:

```css
.bar {
  .foo {
  background-color: black;
}

}
```

Which isn't even valid CSS. Having the ability to e.g. import third-party CSS files and namespace them so that they only apply on a given element would be tremendously useful.
