### ISSUE TITLE
Generated selectors are not callable as mixins

### ISSUE THREAD

**Issue by rytmis** [dotless/dotless#433]
Consider this example:

```less
@var: .mixin;
@{var} {
  // any rules here
}
.test {
  .mixin;
}
```

I'd expect that to work, since logically, `@{var}` expands to `.mixin`. However, currently there are two reasons why it doesn't work:

Variable parsing doesn't accept arbitrary content -- if it doesn't parse as an expression or keyword, we throw an error. This could be worked around like this:

```less
@var: mixin;
.@{var} {
  // any rules here
}
.test {
  .mixin;
}
```

but it still doesn't work, because of reason two: the current evaluation order is last-to-first, so the `@{var}` selector is expanded _after_ the mixin call, and hence doesn't work.

Changing these two things fixes the simple case. However, what I'd really like to see working is a more complex one:

```less
@var: ~".mixin, .mixin2";
@{var} {
  // any rules here
}
.test {
  .mixin2;
}
```

That is, to have the interpolated selector be fully parsed so that any valid selector in the set of selectors would work as a mixin. The reason I'd like to have this feature is so that I could use Bootstrap without having any Bootstrap classes in my markup. To a large extent, this is already possible. Except for columns, because Bootstrap generates its 12-column grid with a more elaborate version of the example above, and hence the .col-size-num selectors aren't extendable or callable as mixins. Which is too bad, because the columns are the *biggest* Bootstrap-related source of cruft in my markup at the moment.

It's worth noting that this doesn't work in less.js either, and there has been some discussion as to how it should be done. The current line of thinking is that it would require evaluating, to-stringing and then re-parsing the selectors. I don't see that as a necessarily bad thing -- the evaluation pass should reduce the selectors to a form where they no longer contain variable references and whatnot, so it's not an infinitely recursive process. However, the implementation is far from simple.

In any case, I'd love to get this in 1.5.
