### ISSUE TITLE
Update luma function to match less and the spec from W3

### ISSUE THREAD

**Issue by mdvorscak** [dotless/dotless#437]
See this commit on the Less project: https://github.com/less/less.js/commit/ea1822385a01711b650894cdd923f5871e497d3a

the current luma function matches the old Less function, this can lead to strange contrasts, for example:

```less
@green: #84C447;
@inverse-green: contrast(@green, #FFF, #333, 60%);

div{
  background: @green; //green
  color:  @inverse-green; //white with less, black with dotless
}
```
