### ISSUE TITLE
@import should be hoisted to the top of the file

### ISSUE THREAD

**Issue by ForNeVeR** [dotless/dotless#440]
For example, the following LESS:

```less
@font-face {
  font-family: "Epsilon";
  src: url('data:font/x-woff;base64,...')
}
@import url(//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700&subset=latin,cyrillic);
```

will be compiled by lessc as the following:

```css
@import url(//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700&subset=latin,cyrillic);
@font-face {
  font-family: "Epsilon";
  src: url('data:font/x-woff;base64,...')
}
```

(it always put URL imports to top)

But dotless cannot do that and compiled CSS becomes invalid in many browsers. Example dotless output:

```css
@font-face {
  font-family: "Epsilon";
  src: url('data:font/x-woff;base64,...')
}
@import url(//fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700&subset=latin,cyrillic);
```
