### ISSUE TITLE
Mixin doesn't pull in &:extend() in 1.5.0-beta3

### ISSUE THREAD

**Issue by WalkerCodeRanger** [dotless/dotless#443]
Tried to upgrade to 1.5.0-beta3 because I really need some Less 1.5.0 features.  Stumbled across this bug in a real world case using bootstrap.  If you use a class containing an extend as a mixin, the extend doesn't apply to the mixed in.  Steps to reproduce:

Use the less code:
```less
.test
{
  color: orange;
}

.replacement
{
	&:extend(.test);
}

.foo
{
	.replacement();
}
```

In dotless 1.5.0-beta3, that compiles to:
```css
.test,
.replacement {
  color: orange;
}
```

Using http://less2css.org, less v1.5.0 it compiles to:
```css
.test,
.replacement,
.foo {
  color: orange;
}
```
Notice how with the official less compiler, `.test` is extended with `.foo`.

I stumbled across this using multiple bootstrap 3.3.2 classes as mixins because they will frequently use `&:extend(.clearfix all);`
