### ISSUE TITLE
RTL plugin cannot handle !important

### ISSUE THREAD

**Issue by Wenjie-Liang** [dotless/dotless#455]
If the float style contain "!important", the value isn't reversed.
.pull-right {
  float: right !important;
}
stay same as LTR.

**Comment by rytmis** [comment]
Thanks for the report -- I'll take a look at this and other smaller changes for 1.5.1 soon.

**Comment by rytmis** [comment]
Are you sure that the results stays the same? I wrote a unit test to verify this behaviour, an what I observed was that:

```less
.rule {
  float: left !important;
}
```

gets transformed to: 

```less
.rule {
  float: right;
}
```

So there is a bug, but the bug is that the !important specifier is lost.
