### ISSUE TITLE
For-each loop with high recursion count outputs garbled text

### ISSUE THREAD

**Issue by JulianLettner** [dotless/dotless#464]
I am using a [for-each helper](https://github.com/seven-phases-max/less.curious/blob/master/src/for.less) in combination with dotless 1.5.0 and encountered a few problems.
All the examples give the expected output when using: http://lesstester.com

```less
@import "for.less";

.for(100); .-each(@i) {
  .xxx {
    color: red;
  }
}
```

Output: garbled, non-printable characters

Note that the less http listener does not throw a stack overflow exception.

When I change it to 10 iterations it works as expected.

**Comment by rytmis** [comment]
What sort of environment are you running in? I tried to reproduce the problem on IIS express, but no luck: with 100 iterations, everything worked fine. With 1000 iterations, I got a stack overflow, which is sort of expected.

Are you compressing output? Is it possible that the garbled output is a result of gzip compression with content that gets truncated?

**Comment by JulianLettner** [comment]
Ha! I lied to you. Sorry!

My test file looked like this:
```less
@import "../bootstrap/bootstrap.less"
@import "for.less";

.for(100); .-each(@i) {
  .xxx {
    color: red;
  }
}
```
If I remove the `@import` for bootstrap (v3.3.5), I get the behavior you describe. Tried to narrow down the issue without success so far...

I am running on IIS express (from Visual Studio 2013). Compression and caching is turned off.

**Comment by rytmis** [comment]
Thanks for the update, I'll take another look at this soon.

**Comment by rytmis** [comment]
I'm assuming you haven't really forgotten the semicolon from the bootstrap import, because that would result in errors, not garbled text. I tried installing `Twitter.Bootstrap.Less` from NuGet, creating a similar directory structure:

```
├───bootstrap
│   │   alerts.less
│   │   ...
│   │   wells.less
│   │
│   └───mixins
│           alerts.less
│           ...
│           vendor-prefixes.less
│
└───test
        for.less
        test.less
```

and then requested the file "/Content/test/test.less" which contains this:

```less
@import "../bootstrap/bootstrap.less";
@import "for.less";

.for(100); .-each(@i) {
  .xxx {
    color: red;
  }
}
```

And the result was... Bootstrap along with the expected 100 repetitions of the .xxx ruleset.

**Comment by JulianLettner** [comment]
I don't know why we get different behavior for the same file, but I found the mistake in my case: I didn't realize that every `for` construct needs to be nested in its own context, otherwise they "share" their iteration count. Example:
```less
@import "for.less"

.for(2); .-each(@i) {
  .abc-@{i} {
    color: red;
  }
}
.for(1); .-each(@i) {
  .xyz-@{i} {
    color: orange;
  }
}
```
Output (this is correct, according to other implementations):
```less
.abc-1 {
  color: red;
}
.xyz-1 {
  color: orange;
}
.abc-2 {
  color: red;
}
.xyz-2 {
  color: orange;
}
.abc-1 {
  color: red;
}
.xyz-1 {
  color: orange;
}

```
This means that I just used the loop wrong. I apologize for stealing your time. :(
I still don't know why I get garbled text for the old test style sheet, but since it only happens for output that I didn't intend to produce anyway ...
Thanks again!
