### ISSUE TITLE
Parent selector (&) not working inside for-each loop construct

### ISSUE THREAD

**Issue by JulianLettner** [dotless/dotless#466]
I am using a [for-each helper](https://github.com/seven-phases-max/less.curious/blob/master/src/for.less) in combination with dotless 1.5.0 and encountered a few problems.
All the examples give the expected output when using: http://lesstester.com

Example from: https://github.com/seven-phases-max/less.curious/blob/master/articles/for-each.md
```less
@import "for.less";

#icon {
    .for(5); .-each(@i) {
        &-@{i} {
            background: red;
        }
    }
}
```

Output:
```
#icon -1 {
  background: red;
}
#icon -2 {
  background: red;
}
...
```

Expected output:
```
#icon-1 {
  background: red;
}
#icon-2 {
  background: red;
}
...
```

Note the additional space in front of `-1`.
