### ISSUE TITLE
Context/scoping issues in loops (loops "share" iteration count)

### ISSUE THREAD

**Issue by JulianLettner** [dotless/dotless#469]
I was too quick to close the previous issue, but since my understanding of the problem got better along the way I thought I create a new issue instead of reopening the old one.

Less:
```less
// ............................................................
// .for

.for(@i, @n) {.-each(@i)}
.for(@n)     when (isnumber(@n)) {.for(1, @n)}
.for(@i, @n) when not (@i = @n)  {
    .for((@i + (@n - @i) / abs(@n - @i)), @n);
}

// ............................................................
// .for-each

.for(@array)   when (default()) {.for-impl_(length(@array))}
.for-impl_(@i) when (@i > 1)    {.for-impl_((@i - 1))}
.for-impl_(@i) when (@i > 0)    {.-each(extract(@array, @i))}

.abc {
  .for(2); .-each(@i) {
    &-@{i} {
      color: red;
    }
  }
}
.xyz {
  .for(2); .-each(@i) {
    &-@{i} {
      color: blue;
    }
  }
}
```
Expected output:
```css
.abc-1 {
  color: red;
}
.abc-2 {
  color: red;
}
.xyz-1 {
  color: blue;
}
.xyz-2 {
  color: blue;
}
```

dotless output:
```css
.abc-1 {
  color: red;
}
.abc-2 {
  color: red;
}
.xyz-1 {
  color: red;
}
.xyz-1 {
  color: blue;
}
.xyz-2 {
  color: red;
}
.xyz-2 {
  color: blue;
}
```
