### ISSUE TITLE
Multiple loops produce garbled text

### ISSUE THREAD

**Issue by JulianLettner** [dotless/dotless#470]
Okay, here is the most minimal file I could discern to produce garbled text.
```less
// ............................................................
// .for

.for(@i, @n) {.-each(@i)}
.for(@n)     when (isnumber(@n)) {.for(1, @n)}
.for(@i, @n) when not (@i = @n)  {
    .for((@i + (@n - @i) / abs(@n - @i)), @n);
}

// ............................................................
// .for-each

.for(@array)   when (default()) {.for-impl_(length(@array))}
.for-impl_(@i) when (@i > 1)    {.for-impl_((@i - 1))}
.for-impl_(@i) when (@i > 0)    {.-each(extract(@array, @i))}



@row-colors: #3f89d0, #a664d4, #f8daa2, #ec7a7a, #ff46ac, #acfb76;
.color {
  .for(length(@row-colors)); .-each(@i) {
    &-@{i} { // color-1, color-2, ...
      color: extract(@row-colors, @i);
    }
  }
}

@category-names:
  unknown, null, ignore, io, latch,       // 1 - 5
  lock, memory, network, backup, clr,     // 5 - 9
  dbm, dtc, servicebroker, sos, waitfor;  // 10 - 14
@category-colors:
  red, red, red, #5bc0de, red,
  #ee5f5b, #b943e9, #fe64cb, red, red,
  red, red, red, red, #f89406;

.category {
  .for(15); .-each(@i) {
    @name: extract(@category-names, @i);
    &-@{name} { // category-io, category-latch, ...
      color: extract(@category-colors, @i);
    }
  }
}
```
It's minimal in the sense that, the output will become non-garbled (on my machine) if I do one of the following
* comment out one of the loops (the other one will work then)
* reduce number of elements in `@row-colors` or `@category-names`
* replace one of the `color: extract(..);` with `color: red;`

Other implementations give me the output I expect.

I have no idea what exactly could trigger this behavior. It's probably best to tackle #469 first and reevaluate.
