### ISSUE TITLE
mixin misbehaviour

### ISSUE THREAD

**Issue by t1l3r** [dotless/dotless#477]
I stumbled upon a mixin misbehaviour which doesn't quite fit my expectations.

Let's say there is a common.less stylesheet which contains the following simplyfied fragment:
```less
.color {
    &01 { ... }
    &02 { ... }
    &BG { background-color: @colorBGDefault; }
}
```
Now I import the common.less in another stylesheet and want to mix-in the class/mixin `.colorBG`.
```less
@import 'common.less';
.box  { .colorBG; }
.grid { .colorBG; }
...
```
My expectation for the rendered output would be:
```less
.box  { background-color: somecolor; }
.grid { background-color: somecolor; }
```
But instead I receive the error *.colorBG is undefined on line ...*.

When I move **&BG** out of the .color block
```less
.color {
    &01 { ... }
    &02 { ... }
}
.colorBG { background-color: @colorBGDefault; }
```
there is no error.
