### ISSUE TITLE
Tampers with calc() (dotless v1.5.2)

### ISSUE THREAD

**Issue by nagilum** [dotless/dotless#514]
If you programatically parse less with the Less.Parse() function to get css, the Less parser tampers with calc().

```css
div { width: calc(100% + 5rem); }
span { width: calc(100% + 5px); }
h1 { width: calc(100% + 5pt); }
```

The following three styles all get written as

```css
div { width: calc(105%); }
span { width: calc(105%); }
h1 { width: calc(105%); }
```

After they have been parsed.
