### ISSUE TITLE
@-moz-document (and universal support for other unsupported attributes)

### ISSUE THREAD

**Issue by axefrog** [dotless/dotless#73]
``` css
@-moz-document url-prefix() {
    h1 {
        color: red;
    }
}
```

dotless totally does not like this selector, which is valid in firefox. To make things easier on yourself, so you don't have to support every obscure vendor definition that comes out, can't you just add a way to escape an attribute name so that it gets parsed "as is"?
