### ISSUE TITLE
Dotless compiler bug - compiler getting confused

### ISSUE THREAD

**Issue by axefrog** [dotless/dotless#78]
Here's a bit of convoluted less code which causes the bug to arise:

``` css
@axefrogstatic: "https://static.axefrog.com/";
@grey8: #f5f5f5;
@grey5: #ccc;
@colorA: #E5225B;
@colorB: #C7C823;

.buttonIcon(@filename) {
    &.fancy {
        @imgbg: formatString("url({0}images/icons/{1})", @axefrogstatic, @filename);
        &:hover {
            background-image: @imgbg, formatString("-webkit-gradient(linear, 0% 0%, 0% 100%, from({0}), to({1}))", @colorA + 30%, @colorA - 20%);
            background-image: @imgbg, formatString("-moz-linear-gradient(0% 100% 90deg,{1}, {0})", @colorA + 30%, @colorA - 20%);
        }
    }
}

.button, button, input[type="submit"] {
    &.lefticon.icon-tick {
        .buttonIcon("fugue/tick.png");
    }
    &.lefticon.icon24-tick.extralarge {
        .buttonIcon("fugue/icons-24/tick.png");
    }
}
```

And the output is:

```
.button.lefticon.icon-tick.fancy:hover, button.lefticon.icon-tick.fancy:hover, input[type="submit"].lefticon.icon-tick.fancy:hover {
  background-image: url(https://static.axefrog.com/images/icons/fugue/tick.png), -webkit-gradient(linear, 0% 0%, 0% 100%, from(#ff4079), to(#d10e47));
  background-image: url(https://static.axefrog.com/images/icons/fugue/tick.png), -moz-linear-gradient(0% 100% 90deg,#d10e47, #ff4079);
}
.button.lefticon.icon24-tick.extralarge.fancy:hover, button.lefticon.icon24-tick.extralarge.fancy:hover, input[type="submit"].lefticon.icon24-tick.extralarge.fancy:hover {
  background-image: url(https://static.axefrog.com/images/icons/fugue/tick.png), -webkit-gradient(linear, 0% 0%, 0% 100%, from(#ff4079), to(#d10e47));
  background-image: url(https://static.axefrog.com/images/icons/fugue/tick.png), -moz-linear-gradient(0% 100% 90deg,#d10e47, #ff4079);
}
```

Notice that the second outputted selector is being generated with the same output as the first text selector, even though it's being passed a different input for `.buttonIcon`.
