### ISSUE TITLE
Problem with function overloading

### ISSUE THREAD

**Issue by macduy** [dotless/dotless#79]
Hi

I'm using **dotLess 1.2.1.0** there seems to be a problem with the way overloaded functions are handled. I have a generic function that creates a linear background, using 2 arguments. I have another version that accepts only 1 colour and computes the other colour by darkening the original one. Here's the sample code `test.less`:

``` css
.gradient(@from, @to)
{
    background: @from;
    background: -moz-linear-gradient(@from, @to);
    background: -o-linear-gradient(@from, @to);
    background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(@from), to(@to));
    background: -khtml-gradient(linear, 0% 0%, 0% 100%, from(@from), to(@to));
    background: -ms-linear-gradient(@from, @to);
    background: linear-gradient(@from, @to);
}

.gradient(@colour) {
    .gradient(@colour, darken(@colour, 10%));
}

.TEST {
    .gradient(#aaaaaa);
}
```

This compiles fine client-side using less.js (http://lesscss.org/). The error given by dotLess is:

```
.gradient is undefined on line 13 in file 'D:\Downloads\dotless-v1.2.1.0\test.less':
 [12]: .gradient(@colour) {
 [13]:     .gradient(@colour, darken(@colour, 10%));
       ----^
 [14]: }
from line 17:
 [17]:     .gradient(#aaaaaa);[Done]
```
